from pathlib import Path
import pandas as pd

DATA_PATH = Path(__file__).resolve().parents[1] / "shared" / "trades.csv"

df = pd.read_csv(DATA_PATH)

"""
1. How many different clients are there in the dataset? Find all the unique clients and number of unique clients.
"""
print(f"Unique Clients:\n{df['client_name'].unique()}")

"""
2. Find the total value generated by each client. Display the highest value client and their total.
"""
print(f"\nMoney Vault\n{df.groupby('client_name')['value'].sum().sort_values(ascending=False)}")

"""
3. Extract only the sell trades - trade_id, client_name, value
Number of Sell Trades
Person with the Most Sell Trades
"""
print("\nSELL-only Trades")
sell_trades = df.loc[df['side'] == 'SELL', ['trade_id', 'client_name', 'value']]
print(f"\n{sell_trades}")
print(f"\nNo. of Sell Trades: {len(sell_trades)}")
print(f"\nPerson with the Most Sell Trades: {sell_trades.groupby('client_name')['value'].count().sort_values(ascending=False).head(1)}")

"""
4. Find every sell trade whose value is greater than 20000
"""
threshold = 5000
summary = sell_trades[sell_trades['value'] > threshold]
print(f"\nEvery Sell Trade with value greater than threshold:\n{summary}")
print(f"\nCount of Trades: {len(summary)}")
print(f"\nTotal Value of Sell Trades: {summary['value'].sum()}")

"""
SUMMARY
"""

print(f"No. of Clients:", len(df['client_name'].unique()))
print(f"Highest Value Client\n", df.groupby('client_name')['value'].sum().sort_values(ascending=False).head(1))
print(f"No. of Sell Trades", len(sell_trades))
print(f"No. of Large Sell Trades (above {threshold}): ", len(summary))
print("One interesting observation: there actually is no sell trade above 20000.")

