spring.application.name=mission-service
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/paysprint_wealth
spring.datasource.username=postgres
spring.datasource.password=n3u3d4!

mybatis.mapper-locations=classpath:mappers/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

jwt.shared-secret=mission-control-shared-secret-key-32-bytes-minimum